### ISSUE TITLE
Null island postal code

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data-postalcode-th#1]
There is at least one, with a bounding box of 0,0,0,0:

https://spelunker.whosonfirst.org/id/437284201/

**Comment by thisisaaronland** [comment]
Many (if not most) postal codes are on Null Island. That reflects the fact that the initial import of postal codes was from the old GeoPlanet dumps which have hierarchy information (so we know what country or city a postal code is part of) but no actual geometries:

https://spelunker.whosonfirst.org/nullisland/?&placetype=postalcode

**Comment by orangejulius** [comment]
Right, I remember this now. Sorry about the noise, it turned out to be incomplete Null Island detection in Pelias.

**Comment by thisisaaronland** [comment]
It's all good. I have been thinking about the rules, etc. for something like an `mz:is_nullisland` flag which is independent of `0.0, 0.0` specifically but rather points to a general need for: Things that exist as a place without necessarily having a location (or, again more precisely, a location that is public).

This would be a "derived" property, dependent on context, in the same way that `mz:is_current` is.

The "nullisland" part would mostly just be a shout-out to the flag's conceptual lineage (in the same way that the `mz:` prefix has been retrofitted to mean "metazen" in a post-Mapzen world...)

Thoughts? Would that be useful? cc: @nvkelso @stepps00

**Comment by stepps00** [comment]
If `mz:is_nullisland` is something we could wire into existing code like `mz:is_current`, I'm all for it.

My concern with a `mz:is_nullisland` property would be that once a record is updated with a geometry, we forget to "unflag" a record as being on null island. But adding it as a "derived" property works for me.

**Comment by thisisaaronland** [comment]
Well, that's the sort of thing that can be trapped/set in the `py-mapzen-whosonfirst-export` code. We already do similar checks for a bunch of flags. The problem of course is that the whole point is that the definition of "Null Island" might vary from context to context, as in a record might have a coordinate in physical space but it doesn't actually _exist_ there. I mean, really that's Null Island (0.0, 0.0) in a nutshell...

So, with all that in mind, I would err towards: Don't forget to update the flag when it's necessary.

Adding @vicchi since maybe his experience with the JSON schema is/can be relevant here.
